In [5]:
import numpy as np

In [8]:
a = np.arange(5)
print(a)

[0 1 2 3 4]


In [7]:
a = np.array([np.arange(2), np.arange(2)])
print(a)

[[0 1]
 [0 1]]


In [9]:
b = np.array([1, 2, 3, 4, 5], ndmin=2)
print(b)

[[1 2 3 4 5]]


In [12]:
c = np.array([1, 2, 3, 4, 5], dtype=complex)
print(c)

[ 1.+0.j  2.+0.j  3.+0.j  4.+0.j  5.+0.j]


In [13]:
dt = np.dtype(np.int64)

In [15]:
dt = np.dtype([('age', np.int8)])
e = np.array([(10,), (20,), (30,)], dtype=dt)
print(e)

[(10,) (20,) (30,)]


In [18]:
dt = np.dtype([('age', np.int8)])
A = np.array([(10,), (20,), (30,)], dtype=dt)
print(A['age'])

[10 20 30]


In [19]:
student = np.dtype([('name', 'S20'), ('age', 'i1'), ('marks', 'f4')])
g = np.array([('Adam', 19, 100), ('Marry', 21, 98), ('Catty', 20, 81)])
print(g)

[['Adam' '19' '100']
 ['Marry' '21' '98']
 ['Catty' '20' '81']]


In [21]:
g = np.array([[1, 2, 3], [4, 5, 6]])
print(g.shape)

(2, 3)


In [22]:
g.shape = (3, 2)
print(g)

[[1 2]
 [3 4]
 [5 6]]


In [37]:
t = np.array([[1, 2], [3, 4], [5, 6]])
print(np.ravel(t))


[1 2 3 4 5 6]


In [41]:
A = np.mat("1 2 3;6 7 9;2 4 3")
b = np.array([1, 2, 3])
x = np.linalg.solve(A, b)
print(x)


[-0.8         1.4        -0.33333333]


In [2]:
import numpy as np
A = np.mat("1 5;-2 -7")
# 上面的双引号里面吗不要加多余的分号
b = np.array([7, -5])
x = np.linalg.solve(A, b)
print(x)

[-8.  3.]
