In [5]:
import numpy as np

In [8]:
a = np.arange(5)
print(a)

[0 1 2 3 4]


In [7]:
a = np.array([np.arange(2), np.arange(2)])
print(a)

[[0 1]
 [0 1]]


In [9]:
b = np.array([1, 2, 3, 4, 5], ndmin=2)
print(b)

[[1 2 3 4 5]]


In [12]:
c = np.array([1, 2, 3, 4, 5], dtype=complex)
print(c)

[ 1.+0.j  2.+0.j  3.+0.j  4.+0.j  5.+0.j]


In [13]:
dt = np.dtype(np.int64)

In [15]:
dt = np.dtype([('age', np.int8)])
e = np.array([(10,), (20,), (30,)], dtype=dt)
print(e)

[(10,) (20,) (30,)]


In [18]:
dt = np.dtype([('age', np.int8)])
A = np.array([(10,), (20,), (30,)], dtype=dt)
print(A['age'])

[10 20 30]


In [19]:
student = np.dtype([('name', 'S20'), ('age', 'i1'), ('marks', 'f4')])
g = np.array([('Adam', 19, 100), ('Marry', 21, 98), ('Catty', 20, 81)])
print(g)

[['Adam' '19' '100']
 ['Marry' '21' '98']
 ['Catty' '20' '81']]


In [21]:
g = np.array([[1, 2, 3], [4, 5, 6]])
print(g.shape)

(2, 3)


In [22]:
g.shape = (3, 2)
print(g)

[[1 2]
 [3 4]
 [5 6]]


In [37]:
t = np.array([[1, 2], [3, 4], [5, 6]])
print(np.ravel(t))


[1 2 3 4 5 6]


In [41]:
A = np.mat("1 2 3;6 7 9;2 4 3")
b = np.array([1, 2, 3])
x = np.linalg.solve(A, b)
print(x)


[-0.8         1.4        -0.33333333]


In [2]:
import numpy as np

A = np.mat("1 5;-2 -7")
# 上面的双引号里面吗不要加多余的分号
b = np.array([7, -5])
x = np.linalg.solve(A, b)
print(x)


[-8.  3.]


In [5]:
A = np.mat("1 5;-2 -7")
inverse = np.linalg.inv(A)
print("Inverse of A:\n")
print(inverse)

Inverse of A:

[[-2.33333333 -1.66666667]
 [ 0.66666667  0.33333333]]


In [6]:
import random
import math

# 假设迭代次数为10000
n = 10000
total = 0  # total是所有落入圆内的随机点
for i in range(0, n):
    x = random.random()
    y = random.random()
    if math.sqrt(x ** 2 + y ** 2) < 1.0:  # 判断是否落入圆内
        total += 1
mypi = 4.0 * total / n  # 得到Pi值
print('Pi的值是：', mypi)
print("数学pi：", math.pi)
print("误差是：", abs(math.pi - mypi) / math.pi)  # 计算误差


Pi的值是： 3.1372
数学pi： 3.141592653589793
误差是： 0.0013982250642118699


In [1]:
import numpy as np
def integrate(f, a, b, N):    # N是 曲线a到b的面积分为多少个小长方形，分的越多越精确
    x = np.linspace(a, b, N)
    fx = f(x)
    area = np.sum(fx)*(b-a)/N
    return area



In [3]:

integrate(np.sin, 0, np.pi/2, 100)

0.99783321217729826

In [ ]:
def integrate(f, a, b, N):
    x = np.linspace(a + (b - a) / (2 * N), b - (b - a) / (2 * N), N)
    fx = f(x)
    area = np.sum(fx) * (b - a) / N
    return area


integrate(np.sin, 0, np.pi / 2, 100)


1.0000102809119051